###

ModelConfig:

  model_version: "v1"
  model_path: "challenge/models"
  test_set_rate: 0.33
  threshold_in_minutes: 15.0

  default_model_params:
    random_state: 1
    learning_rate: 0.01
  
  training_features:
    # Features to encode as one-hot vectors, the inside values are the one allowed for training.
    categorical:
      OPERA:
        - Latin American Wings
        - Grupo LATAM
        - Sky Airline
        - Copa Air

      MES:
        - 7
        - 10
        - 12
        - 4
        - 11
      
      TIPOVUELO:
        - I
    
    # Other features no encoded
    default:

      
ApiConfig:
  models:
    FlightModel:
      OPERA:
        - American Airlines
        - Air Canada
        - Air France
        - Aeromexico
        - Aerolineas Argentinas
        - Austral
        - Avianca
        - Alitalia
        - British Airways
        - Copa Air
        - Delta Air
        - Gol Trans
        - Iberia
        - K.L.M.
        - Qantas Airways
        - United Airlines
        - Grupo LATAM
        - Sky Airline
        - Latin American Wings
        - Plus Ultra Lineas Aereas
        - JetSmart SPA
        - Oceanair Linhas Aereas
        - Lacsa
      MES:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
      
      TIPOVUELO:
        - 'I'
        - 'N'