name: 'Continuous Delivery'

on:
  push:
    branches: [ "main", "develop", "feature/part4-run-tests" ]
  pull_request:
    branches: [ "main", "develop", "feature/part4-run-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make install

    - name: Run model train
      run: make model-train
    
    - name: build
      run: |
        docker  build . -t dcasalsamat/challenge-mle:${GITHUB_REF##*/}
    
    - name: publish
      run: |
        docker push dcasalsamat/challenge-mle:${GITHUB_REF##*/}
      