name: 'Continuous Delivery'

on:
  push:
    branches: [ "main", "develop", "feature/part4-run-tests" ]
  pull_request:
    branches: [ "main", "develop", "feature/part4-run-tests" ]

env:
  PROJECT_ID: challengemle # TODO: update Google Cloud project id
  SERVICE: challenge-mle # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make install

    - name: Run model train
      run: make model-train
    
    - name: build
      run: |
        docker  build . -t dcasalsamat/challenge-mle:${{ github.sha }}
    
    - name: publish
      run: |
        docker login -u dcasalsamat -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push dcasalsamat/challenge-mle:${{ github.sha }}

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

    - name: Deploy to Cloud Run
      id: deploy
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        # NOTE: If using a pre-built image, update the image name here
        image: dcasalsamat/challenge-mle:${{ github.sha }}

    # If required, use the Cloud Run url output in later steps
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}