name: 'Continuous Integration'


on:
  push:
    branches: [ "main", "develop", "feature/part4-run-tests" ]
  pull_request:
    branches: [ "main", "develop", "feature/part4-run-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Run model tests
      run: make model-test

    - name: Run api-test
      run: make api-test